image: docker:20.10.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERT_DIR: ""
  INTERNAL_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

services:
  - docker:20.10.10-dind

stages:
  - build
  - test
  - push

default:
  tags:
    - ht-docker

container_scanning:
  variables:
    TRIVY_TIMEOUT: "1h"

include:
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $INTERNAL_IMAGE_TAG .
    - docker push $INTERNAL_IMAGE_TAG
  timeout: 2h

hub_release:
  stage: push
  variables:
    PUBLISH_TAG: hub.es.net:5000/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    GIT_STRATEGY: none
  script:
    # Auth and pull the image from gitlab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $INTERNAL_IMAGE_TAG

    # Tag the image for release
    - docker tag $INTERNAL_IMAGE_TAG $PUBLISH_TAG

    # Push to external registry
    - docker push $PUBLISH_TAG
  timeout: 2h
  rules:
    - if: $CI_COMMIT_TAG

wharf_release:
  stage: push
  variables:
    # example PUBLISH_TAG: wharf.es.net/ht/xilinx-labtools-docker:v2021.2-1
    PUBLISH_TAG: $HSITE/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    GIT_STRATEGY: none
  script:
    # Auth and pull the image from gitlab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $INTERNAL_IMAGE_TAG

    # Tag the image for release
    - docker tag $INTERNAL_IMAGE_TAG $PUBLISH_TAG

    # Auth and push to external registry
    - docker login -u "$HUSER" -p "$HTOKEN" "$HSITE"
    - docker push $PUBLISH_TAG
  timeout: 2h
  rules:
    - if: $CI_COMMIT_TAG
