image: docker:20.10.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERT_DIR: ""
  ESNET_REGISTRY: "hub.es.net:5000"
  RELEASE_BRANCH: "main"
  LATEST_TAG: $ESNET_REGISTRY/$CI_PROJECT_NAME:latest
  INTERNAL_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

services:
  - docker:20.10.10-dind

stages:
  - build
  - test
  - push

default:
  tags:
    - ht-docker

include:
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $INTERNAL_IMAGE_TAG .
    - docker push $INTERNAL_IMAGE_TAG
  timeout: 2h

.push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $INTERNAL_IMAGE_TAG
    - docker tag $INTERNAL_IMAGE_TAG $PUBLISH_TAG
    - docker push $PUBLISH_TAG
    - if [ "${PUBLISH_LATEST}" == "true" ]; then docker tag $INTERNAL_IMAGE_TAG $LATEST_TAG && docker push $LATEST_TAG; fi
  timeout: 2h

internal_release:
  extends:
    - .push
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    PUBLISH_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    GIT_STRATEGY: none

external_release:
  extends:
    - .push
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    PUBLISH_TAG: $ESNET_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    GIT_STRATEGY: none

