include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'security/container-scanning'
    file: '.ESnet-container-scan.yml'

build:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  tags:
    - ht-docker
  variables:
    # example PUBLISH_TAG: wharf.es.net/ht/xilinx-labtools-docker:18106-g1b221f5c
    PUBLISH_TAG: $HSITE/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID-g$CI_COMMIT_SHORT_SHA
  script:
    # Auth to external registry
    - docker login -u "$HUSER" -p "$HTOKEN" "$HSITE"
    # Build and push
    - docker build --pull -t $PUBLISH_TAG$TAG_SUFFIX .
    - docker push $PUBLISH_TAG$TAG_SUFFIX
    # Capture the published tag for downstream CI jobs
    - |
      cat <<EOF >> build.env
      CS_IMAGE=$PUBLISH_TAG$TAG_SUFFIX
      EOF
    - cat build.env
  timeout: 2h
  artifacts:
    reports:
      dotenv:
        build.env
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        TAG_SUFFIX: -dev

container_scanning:
  variables:
    CS_REGISTRY_USER: $HUSER_RO
    CS_REGISTRY_PASSWORD: $HTOKEN_RO
    TRIVY_TIMEOUT: "1h"
  # use 'dependencies' here rather than 'needs' since the gitlab container scanning
  # include sets 'dependencies: []' which takes precedence over 'needs'
  dependencies:
    - build

