services:
  xilinx-hwserver:
    container_name: xilinx-hwserver
    hostname: xilinx-hwserver
    image: xilinx-labtools-docker:v2022.1-latest
    build:
      context: .
    init: true
    privileged: true
    ports:
      - "3121:3121"
      - "1534:1534"
    volumes:
      - /dev:/dev
      - /sys/bus/usb:/sys/bus/usb
    entrypoint:
      - /bin/bash
      - -c
      - -e
      - -o
      - pipefail
      - -x
      - |
        /opt/Xilinx/Vivado_Lab/$${VIVADO_VERSION}/bin/hw_server \
          -S \
          -s \
          tcp::3121
